### PR TITLE
Fix/Login Issues

### LINKED ISSUE #159: Unexpected behaviours on user Login
Please update this description with a piece of detailed information about the issue.

### PR DESCRIPTION
**Pull request by RodriSanchez1**
close #159

### CODE REVIEW

File: src/app/[locale]/signin/Login/Dialog.tsx [hunk 1]
```diff
@@ -36,7 +37,9 @@ export default function Dialog({
           const response = await signIn('credentials', {
             email: formData.get('email') as string,
             password: formData.get('password') as string,
-            callbackUrl: DEFAULT_CALLBACK_URL,
+            callbackUrl: locale
+              ? `/${locale}/${DEFAULT_CALLBACK_URL}`
```
Comment (RodriSanchez1) [inline src/app/[locale]/signin/Login/Dialog.tsx:41]: TODO: Improve redirections with locale to avoid unnecesary middleware redirects
